# Generated by Django 4.2.2 on 2023-08-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupProductImage',
        ),
        migrations.RemoveField(
            model_name='paidversion',
            name='shop_id',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImageId',
        ),
        migrations.DeleteModel(
            name='PaidVersion',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
